trigger:
- master

pool:
  vmImage: ubuntu-latest

extends:
   template: build.generic.yml
   parameters:
     postBuildSteps: 
       - task: Docker@2
         inputs:
           containerRegistry: 'Github Packages'
           repository: todoItemsApi
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'
           buildContext: '$(Build.ArtifactStagingDirectory)/todoItemsApi'
