name: Build TodoItems
on: 
  schedule:
    - cron:  '0 0 * * 3'
  push:
    paths-ignore:
      - '.azuredevops/**'
  workflow_dispatch:
    inputs:
      buildConfiguration:
        description: 'Build configuration'
        required: true
        default: 'Release' 
        type: choice
        options:
        - Debug
        - Release
defaults:
  run:
    shell: pwsh
jobs:
  determine_variables:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ steps.setupVars.outputs.buildConfiguration }}
    steps:
    - name: Setup variables
      id: setupVars
      run: |
        if("${{inputs.buildConfiguration}}"){
          echo "buildConfiguration=${{inputs.buildConfiguration}}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
        else{
          echo "buildConfiguration=Release" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
  build:  
    needs: [determine_variables]
    uses: ./.github/workflows/build.yml
    with:
      buildConfiguration: ${{needs.determine_variables.outputs.buildConfiguration}}
    secrets: inherit
  deploy_bicep:
    needs: [build]
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: infraCode
          path: ${{github.workspace}}/artifacts/bicep

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION }}
          resourceGroupName: 'Temp1'
          template: ${{github.workspace}}/artifacts/bicep/main.nodocker.webapp.bicep
          parameters: '${{github.workspace}}/artifacts/bicep/main.nodocker.webapp.parameters.json sqlAdministratorLoginPassword=${{secrets.AZURE_SQL_PASSWORD}}'
