name: Build TodoItems
on: 
  schedule:
    - cron:  '0 0 * * 3'
  push:
    paths-ignore:
      - '.azuredevops/**'
  workflow_dispatch:
    inputs:
      buildConfiguration:
        description: 'Build configuration'
        required: true
        default: 'Release' 
        type: choice
        options:
        - Debug
        - Release
defaults:
  run:
    shell: pwsh
jobs:
  build:
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{secrets.SA_PASSWORD}}
          MSSQL_PID: Developer
        options: --name mssql
        ports:
          - 1433:1433
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: '${{github.workspace}}/.nuget/packages'
      testDatabasename: 'TodoItemDB'
    steps:
    - name: Setup variables
      run: |
        if("${{github.event.inputs.buildConfiguration}}"){
          echo "buildConfiguration=${{github.event.inputs.buildConfiguration}}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        }
        else{
          echo "buildConfiguration=Release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        }
    
    - uses: actions/checkout@v3
    
    - uses: actions/setup-dotnet@v3
    
    - name: Restore cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{env.NUGET_PACKAGES}}
        key: ${{runner.os}}-build-${{ hashFiles('**/packages.lock.json', '!**/bin/**', '!**/obj/**') }}
   
      #If the cache has been restored, the deps.json isn't generated. In order to generate this we will do a dotnet build.
    - name: Dotnet build - cache restored
      if: ${{steps.cache.outputs.cache-hit == 'true'}}
      run: dotnet build --configuration ${{env.buildConfiguration}}
    
    - name: Dotnet restore
      if: ${{steps.cache.outputs.cache-hit != 'true'}}
      run: dotnet restore --locked-mode --nologo
    
    - name: Dotnet build - no cache
      if: ${{steps.cache.outputs.cache-hit != 'true'}}
      run: dotnet build --no-restore --configuration ${{env.buildConfiguration}}
    
    - name: Restore tools
      run: dotnet tool restore
      working-directory: ${{github.workspace}}/TodoItems.Api
    
    - name: Create idempotent SQL scripts
      run: dotnet ef migrations script --output '${{github.workspace}}/artifacts/SQL/db.sql' --idempotent --project TodoItems.Api.csproj --context TodoDb --no-build --configuration ${{env.buildConfiguration}} 
      working-directory: ${{github.workspace}}/TodoItems.Api
      env:
        #Pass environment variable dummy. So the migration script will not be created against the InMemory database.
        ASPNETCORE_ENVIRONMENT: 'DUMMY'
    
    - name: Create database for integration tests
      run: |
          sqlcmd -S 127.0.0.1,1433 -U SA -P '${{secrets.SA_PASSWORD}}' -Q 'CREATE DATABASE ${{env.testDatabasename}}' -b
          sqlcmd -S 127.0.0.1,1433 -U SA -P '${{secrets.SA_PASSWORD}}' -i db.sql -d ${{env.testDatabasename}} -b
      working-directory: '${{github.workspace}}/artifacts/SQL'
      timeout-minutes: 1  
    
    - name: Run tests
      run: dotnet test --no-build --configuration ${{env.buildConfiguration}} --logger:"console;verbosity=detailed"
      env:
        integrationtests_ConnectionStrings__TodoDb: 'Server=127.0.0.1,1433;Database=${{env.testDatabasename}};User Id=SA;Password=${{secrets.SA_PASSWORD}};TrustServerCertificate=true;'
    
    - name: Publish API
      run: dotnet publish ${{github.workspace}}/TodoItems.Api/TodoItems.Api.csproj --configuration ${{env.buildConfiguration}} --no-build --output ${{github.workspace}}/artifacts/TodoItems.Api
    
    - name: Publish SQL artifact
      uses: actions/upload-artifact@v3
      with:
        name: database
        path: '${{github.workspace}}/artifacts/SQL'
        if-no-files-found: error
    
    - name: Publish Bicep artifact
      uses: actions/upload-artifact@v3
      with:
        name: infraCode
        path: '${{github.workspace}}/Deployment/**'
        if-no-files-found: error
    
    - name: Publish API artifact
      uses: actions/upload-artifact@v3
      with:
        name: todoItemsApi
        path: '${{github.workspace}}/artifacts/TodoItems.Api/**'
        if-no-files-found: error
