name: Build TodoItems Docker
on: 
  schedule:
    - cron:  '0 0 * * 3'
  push:
    paths-ignore:
      - '.azuredevops/**'
  workflow_dispatch:
    inputs:
      buildConfiguration:
        description: 'Build configuration'
        required: true
        default: 'Release' 
        type: choice
        options:
        - Debug
        - Release
defaults:
  run:
    shell: pwsh
jobs:
  determine_variables:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ steps.setupVars.outputs.buildConfiguration }}
    steps:
    - name: Setup variables
      id: setupVars
      run: |
        if("${{github.event.inputs.buildConfiguration}}"){
          echo "buildConfiguration=${{github.event.inputs.buildConfiguration}}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
        else{
          echo "buildConfiguration=Release" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
  build:  
    needs: [determine_variables]
    uses: ./.github/workflows/build.yml
    with:
      buildConfiguration: ${{needs.determine_variables.outputs.buildConfiguration}}
    secrets: inherit
  push_docker_image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: todoItemsApi
      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4.1.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
