name: Build TodoItems
on: 
  schedule:
    - cron:  '0 0 * * 3'
  push:
    paths-ignore:
      - '.azuredevops/**'
  workflow_dispatch:
    inputs:
      buildConfiguration:
        description: 'Build configuration'
        required: true
        default: 'Release' 
        type: choice
        options:
        - Debug
        - Release
defaults:
  run:
    shell: pwsh
jobs:
  determine_variables_build:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ steps.setupVars.outputs.buildConfiguration }}
    steps:
    - name: Setup variables
      id: setupVars
      run: |
        if("${{inputs.buildConfiguration}}"){
          echo "buildConfiguration=${{inputs.buildConfiguration}}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
        else{
          echo "buildConfiguration=Release" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
  build:  
    needs: [determine_variables_build]
    uses: ./.github/workflows/build.yml
    with:
      buildConfiguration: ${{needs.determine_variables_build.outputs.buildConfiguration}}
    secrets: inherit
  
  determine_variables_deploy:
    runs-on: ubuntu-latest
    outputs:
      resourcegroup: ${{ steps.setupResourcegroup.outputs.resourcegroup }}
    steps:
       - name: Setup variables
         id: setupResourcegroup
         run: |
            $randomNumber = Get-Random -Minimum 10000000000 -Maximum 99999999999
            echo "resourcegroup=todoItems-$randomNumber" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

  create_env:
    needs: [build, determine_variables_deploy]
    runs-on: ubuntu-latest
    outputs:
      webAppName: ${{ steps.arm.outputs.webAppName }}
    environment: AzureProvision
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: infraCode
          path: ${{github.workspace}}/artifacts/bicep

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/CLI@v1
        with:
          inlineScript: az group create --location ${{ secrets.DATACENTER }} --name ${{ needs.determine_variables_deploy.outputs.resourcegroup }}

      - uses: azure/arm-deploy@v1
        id: arm
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION }}
          resourceGroupName: ${{ needs.determine_variables_deploy.outputs.resourcegroup }}
          template: ${{github.workspace}}/artifacts/bicep/main.nodocker.webapp.bicep
          parameters: '${{github.workspace}}/artifacts/bicep/main.nodocker.webapp.parameters.json sqlAdministratorLoginPassword=${{secrets.AZURE_SQL_PASSWORD}}'
  deploy_app:
    needs: [build, determine_variables_deploy, create_env]
    runs-on: ubuntu-latest
    environment: AzureDeploy
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: todoItemsApi
          path: ${{github.workspace}}/artifacts/api
          
      - uses: azure/CLI@v1
        with:
          inlineScript: az group create --location ${{ secrets.DATACENTER }} --name ${{ needs.determine_variables_deploy.outputs.resourcegroup }}
          
      - uses: Azure/webapps-deploy@v2.2.5
        with:
          app-name: ${{ needs.create_env.outputs.webAppName }} 
          package: ${{github.workspace}}/artifacts/api
  delete_env:
    runs-on: ubuntu-latest
    needs: [determine_variables_deploy, deploy_app]
    environment: AzureRemove
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: azure/CLI@v1
        with:
          inlineScript: az group delete --name ${{ needs.determine_variables_deploy.outputs.resourcegroup }} --yes
